server:
  port: 9001
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
    threads:
      max: 64
      min-spare: 4
  shutdown: graceful

recommendation:
  game-genre: SPORTS
  game-title: NHL 23

feature-flags:
  in-memory-storage: false

spring:
  application:
    name: catalog-service
  lifecycle:
    timeout-per-shutdown-phase: 20s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 3000
      fail-fast: false
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.5
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/gamecloud_catalog
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 8
#  sql:
#    init:
#      mode: always  # to initialize the db from resources/schema.sql

management:
  endpoints:
    web:
      exposure:
        include: refresh
