server:
  port: 9001
  tomcat:
    connection-timeout: 3s
    keep-alive-timeout: 20s
    threads:
      max: 64
      min-spare: 4

recommendation:
  game-genre: SPORTS
  game-title: NHL 23

feature-flags:
  in-memory-storage: true

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 5000
      request-read-timeout: 3000
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 1000
        max-interval: 5000
        multiplier: 1.5

management:
  endpoints:
    web:
      exposure:
        include: refresh
