apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: gamecloud-catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                # Delay SIGTERM signal to Pod, so that K8s has enough time to inform other components. To ensure that e.g. the
                # service registry is updated, no requests are forward to the terminating pod anymore due to race condition.
                command: [ "sh", "-c", "sleep 3" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://gamecloud-postgres/gamecloud_catalog
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_PROFILES_ACTIVE
              value: demo
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://gamecloud-keycloak/realms/GameCloud
